service: deep-detect
runtime: python310
entrypoint: gunicorn -b :$5000 app.main:app

env_variables:
  FLASK_APP: "app.main"
  FLASK_ENV: "production"

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
