version: '3.8'

services:
  deep-detect-ai:
    build: .
    container_name: deep-detect-ai
    networks:
      - deep-detect-network
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-here
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  deep-detect-network:
    external: true 